export const TOGGLE_NAV = "TOGGLE_NAV";
export const SAVE_LIST = "SAVE_LIST"
export const DETAIL_MOVIES = "DETAIL_MOVIES";
export const GET_UPCOMING = "GET_UPCOMING";
export const GET_POPULAR = "GET_POPULAR";
export const GET_NOWPLAYING = "GET_NOWPLAYING";
export const GET_TOP_RATED = "GET_TOP_RATED";
export const GET_DETAILS = "GET_DETAILS";
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_GENRES ="GET_GENRES";